### ISSUE TITLE
Error using bed_venn3.py on HPC

### ISSUE THREAD

**Issue by varsh1090** [zhoulab/bedvenn#1]
Command: 
module load python
python bed_venn3.py P53-GFP_modERN_idr.bed P53-GFP_modERN_peaks.bed HQPeaks_8sam.bed HC_modERN_venn.png

Error:
Traceback (most recent call last):
  File "bed_venn3.py", line 16, in <module>
    raise Exception('Must provide 3 BED files.')
Exception: Must provide 3 BED files.

Is there any other requirement to use the script on HPC? Please verify, thanks.

**Comment by victorlin** [comment]
Fixed the issue. Additionally, you'll need to use a python virtual environment with the requirements installed. I've already made one in the bioinformatics directory. You can activate it using this command:

    $ source /ufrc/zhou/share/projects/bioinformatics/hpc_set_env
    $ python bed_venn3.py P53-GFP_modERN_idr.bed P53-GFP_modERN_peaks.bed HQPeaks_8sam.bed HC_modERN_venn.png

**Comment by varsh1090** [comment]
I see, thanks Victor!

**Comment by varsh1090** [comment]
HI Victor, I still see the same error in the HPC ve -
[v.sundaresan@gator3 ValidSamples]$ source /ufrc/zhou/share/projects/bioinformatics/hpc_set_env
(ve) [v.sundaresan@gator3 ValidSamples]$ python bed_venn3.py P53-GFP_modERN_idr.bed P53-GFP_modERN_peaks.bed HQPeaks_8sam.bed HC_modERN_venn.png
Traceback (most recent call last):
  File "bed_venn3.py", line 16, in <module>
    raise Exception('Must provide 3 BED files.')
Exception: Must provide 3 BED files.

**Comment by victorlin** [comment]
Did you use the updated `bed_venn3.py` file?

**Comment by varsh1090** [comment]
I did now and it seems to work. Is it possible to also use this for 2 beds instead of 3? Please lmk, thanks!

**Comment by victorlin** [comment]
Yes, I'll add the functionality tomorrow.
